### ISSUE TITLE
bug: track duration parsing fails for 1hr+ long tracks

### ISSUE THREAD

**Issue by smopucilowski** [Serhii-DV/bandcamp-to-discogs#122]
The final track in this release:

https://coppicehalifax.bandcamp.com/album/deep-earth-year-three-compleat

has a duration of 1:12:46. This fails to get parsed as a track duration on the discogs draft submission page, and the duration is instead added to the track title.

**Comment by Serhii-DV** [comment]
Thanks for the feedback. Yes, there are some issues with durations.
